zdevops.classic.connection.title=z/OS connection
zdevops.classic.datasetName.title=Dataset name
zdevops.classic.isLocalPath.title=Use local path
zdevops.classic.isLocalPath.description=Flag indicating if the provided path is local (true) or relative to the Jenkins build workspace (false)

zdevops.classic.dir.title=Path to the directory