zdevops.classic.connection.title=z/OS connection
zdevops.classic.dsn.title=Dataset
zdevops.classic.dsn.desc=Specify a dataset as HLQ.DSNAME or a member name as HLQ.DSNAME(MEMNAME)
zdevops.classic.failOnNotExist.title=Fail the step if the entity does not exist
