name: Maven build

on:
  workflow_dispatch:
  push:
    branches:
      - 'release/*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout of github repository
        uses: actions/checkout@v3

      - name: Setup of environment
        uses: ./.github/setup

      - name: Check repository content
        shell: bash
        run: pwd && ls -la

      - name: Maven wrapper
        shell: bash
        run: mvn wrapper:wrapper

      - name: Test run
        shell: bash
        run: ./mvnw clean verify

      - name: Sonarcloud scans
        uses: ./.github/sonar
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

      - name: Plugin build
        shell: bash
        run: ./mvnw clean compile hpi:hpi

      - name: Verify content of target folder
        shell: bash
        run: pwd && ls -l target/

      - name: Publish built plugin
        uses: actions/upload-artifact@v3
        with:
          name: builtPlugin
          path: ./target/zdevops.hpi
