name: Jenkins plugin .hpi build

# This workflow will build an executable Jenkins plugin in .hpi format for further manual installation in Jenkins

on: [push, workflow_dispatch]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Jenkins plugin code
        uses: actions/checkout@v4

      - name: Check repository content
        shell: bash
        run: pwd && ls -la

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build Jenkins Plugin into .hpi
        shell: bash
        run: mvn clean package  # Build the plugin using Maven

      - name: Verify content of target folder
        shell: bash
        run: pwd && ls -l target/

      - name: Archive the Build Output
        uses: actions/upload-artifact@v4
        with:
          name: Zowe zDevOps plugin
          path: target/*.hpi